FROM golang:1.25 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3.23.3

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT /usr/bin/frpc -c /etc/frp/frpc.ini
