FROM golang:1.25 AS building

COPY . /building
WORKDIR /building

RUN make frps

FROM alpine:3.24.1

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT /usr/bin/frps -c /etc/frp/frps.ini
