FROM golang:1.27 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3.24.2

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT /usr/bin/frpc -c /etc/frp/frpc.ini
